version: 2

mkdocs:
  configuration: mkdocs.yml

build:
  os: "ubuntu-24.04"
  tools:
    python: "3.12"

  jobs:
    post_create_environment:
      - pip install poetry

    post_install:
      - poetry install --only doc
      - poetry run python -c "import material; print(material.__file__)"
      - poetry run mkdocs build --clean --site-dir $READTHEDOCS_OUTPUT/html --config-file mkdocs.yml
