version: 2

mkdocs:
  configuration: mkdocs.yml

build:
  os: "ubuntu-24.04"
  tools:
    python: "3.12"

  jobs:
    post_install:
      - pip install doc
      - python -m pip show mkdocs-material
      - python -c "import sys; print(sys.executable)"
      - python -c "import site; print(site.getsitepackages())"
