site_name: Notas musicais
repo_url: https://github.com/renatoksxd/notas-musicais
repo_name: renatoksxd/notas-musicais
edit_uri: tree/main/docs

theme: 
    name: material
    language: pt-BR
    logo: assets/logo notas musicais.png
    favicon: assets/logo notas musicais.png

markdown_extensions:
  - attr_list

extra_css:
  - stylesheets/extra.css

watch:
  - src/notas_musicais

plugins:
- mkdocstrings:
    handlers:
      python:
        paths: [src\notas_musicais]